import useSWR from 'swr';
import Head from 'next/head';

import { Loader, Container } from '@mantine/core';

import SiteHeader from 'components/SiteHeader';
import UsersTable from 'components/UsersTable';
import { fetchWithToken } from 'utils/common';
import { User } from 'types/data';

// Snag fifty random users from the API
const dataUrl = 'https://randomuser.me/api/?results=50';
const sampleToken = 'sample token';

export default function Home() {
	// Retrieve example user data from API
	const { data, error } = useSWR([dataUrl, sampleToken], ([url, token]) =>
		fetchWithToken(url, token),
	);

	if (!data && !error) {
		return (
			<>
				<SiteHeader userName="rick.li" />
				<Container size="lg" style={{ textAlign: 'center' }}>
					<Loader />
				</Container>
			</>
		);
	}

	const users: User[] = data.results;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SiteHeader userName="rick.li" />
			<Container size="lg">
				<UsersTable users={users} />
			</Container>
		</>
	);
}
